name: Nikto Scanner

on:
  push:
    branches:
      - main

jobs:
  nikto-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Perl
      run: |
        sudo apt-get update
        sudo apt-get install -y perl

    - name: Navigate to Nikto directory
      run: cd path/to/nikto

    - name: Run Nikto
      run: |
        perl nikto.pl -h http://juice-shop.herokuapp.com/#/
