name: Nikto Scanner

on:
  push:
    branches:
      - main

jobs:
  nikto-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Perl and Git
      run: |
        sudo apt-get update
        sudo apt-get install -y perl git

    - name: Download nikto.pl
      run: |
        curl -O https://raw.githubusercontent.com/sullo/nikto/master/program/nikto.pl

    - name: Run Nikto
      run: perl ./nikto.pl -h http://juice-shop.herokuapp.com/
