name: Analisar Vulnerabilidades do OWASP ZAP
on:
  push:
    branches:
      - main

jobs:
  analisar-vulnerabilidades:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Instalar Dependências
      run: npm install

    - name: Executar OWASP ZAP
      run: |
        npm run zap-command http://juice-shop.herokuapp.com > zap-output.json
        echo '{"vulnerabilities": [{"name": "Vuln1", "severity": "High"}, {"name": "Vuln2", "severity": "Medium"}]}' > zap-output.json
