name: Análise de OWASP ZAP

on:
  push:
    branches:
      - main

jobs:
  owasp-zap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Instalar dependências
        run: npm install
        
      - name: Atualizar npm
        run: npm install -g npm@latest

      - name: Remover ZAP-CLI existente
        run: npm uninstall -g zap-cli || true

      - name: Instalar build-essential
        run: sudo apt-get install -y build-essential



      - name: Instalar ZAP-CLI
        run: sudo npm install -g zap-cli


      - name: Executar análise do OWASP ZAP
        run: zap-cli --quickurl http://seusite.com -c 1 -r relatorio-owasp.html


      - name: Analisar resultado
        run: node analisar-linha.js
